[package]
name = "shake256-demo"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
risc0-zkvm  = { version = "2.3.1", features = ["std", "prove"] }
anyhow     = "1.0"
hex         = "0.4"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
hkdf = "0.12"
sha3 = "0.10"
serde-big-array = "0.5"

[dev-dependencies]
rand = "0.8"
cipher = { version = "0.4", features = ["std"] }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }




[build-dependencies]
risc0-build = "2.3.1"

[package.metadata.risc0]
methods = ["methods/guest"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(rust_analyzer)'] }


