use std::u128;

// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use transfer_methods::{
    TRANSFER_ELF, TRANSFER_ID
};
use outer_methods::{
    OUTER_ELF, OUTER_ID
};
use risc0_zkvm::{default_executor, default_prover, ExecutorEnv, Receipt};
use toy_example_core::Account;

fn prove_inner(sender: Account, receiver: Account, balance_to_move: u128) -> (Receipt, Account, Account) {
    let mut env_builder = ExecutorEnv::builder();
    env_builder.write(&sender).unwrap();
    env_builder.write(&receiver).unwrap();
    env_builder.write(&balance_to_move).unwrap();
    let env = env_builder.build().unwrap();

    let prover = default_prover();
    let prove_info = prover
        .prove(env, TRANSFER_ELF)
        .unwrap();

    let receipt = prove_info.receipt;

    let output: [Account; 4] = receipt.journal.decode().unwrap();
    let [_, _, sender_post, receiver_post] = output;

    println!("sender_before: {:?}, sender_after: {:?}", sender, sender_post);
    println!("receiver_before: {:?}, receiver_after: {:?}", receiver, receiver_post);

    // Sanity check
    receipt
        .verify(TRANSFER_ID)
        .unwrap();

    (receipt, sender_post, receiver_post)
}

pub fn run_private_execution_of_transfer_program() {
    let commitment_tree_root = [0xdd, 0xee, 0xaa, 0xdd, 0xbb, 0xee, 0xee, 0xff];
    let sender_private_key = [0; 8];
    let mut sender = Account::new(sender_private_key, [1; 8]);
    sender.balance = 150;

    let receiver_private_key = [99; 8];
    let receiver = Account::new(receiver_private_key, [1; 8]);
    let balance_to_move: u128 = 3;

    // Prove inner
    let (inner_receipt, sender_post, receiver_post) = prove_inner(sender.clone(), receiver.clone(), balance_to_move);

    // Prover outer
    let mut env_builder = ExecutorEnv::builder();
    env_builder.add_assumption(inner_receipt);
    env_builder.write(&sender_private_key).unwrap();
    env_builder.write(&sender).unwrap();
    env_builder.write(&receiver) .unwrap();
    env_builder.write(&balance_to_move).unwrap();
    env_builder.write(&sender_post).unwrap();
    env_builder.write(&receiver_post).unwrap();
    env_builder.write(&commitment_tree_root).unwrap();
    env_builder.write(&TRANSFER_ID).unwrap();
    let env = env_builder.build().unwrap();

    let prover = default_prover();
    let prove_info = prover
        .prove(env, OUTER_ELF)
        .unwrap();

    let receipt = prove_info.receipt;
    
    // Sanity check
    receipt.verify(OUTER_ID).unwrap();
    
    let output: [[u32; 8]; 3] = receipt.journal.decode().unwrap();
    println!("nullifier: {:?}", output[0]);
    println!("commitment_1: {:?}", output[1]);
    println!("commitment_2: {:?}", output[2]);
}

pub fn run_public_execution_of_transfer_program() {
    let sender_private_key = [0; 8];
    let mut sender = Account::new(sender_private_key, [1; 8]);
    sender.balance = 150;

    let receiver_private_key = [99; 8];
    let mut receiver = Account::new(receiver_private_key, [1; 8]);
    receiver.balance = 900;

    let balance_to_move: u128 = 3;

    let mut env_builder = ExecutorEnv::builder();
    env_builder.write(&sender).unwrap();
    env_builder.write(&receiver).unwrap();
    env_builder.write(&balance_to_move).unwrap();
    let env = env_builder.build().unwrap();

    let executor = default_executor();
    let result: [Account; 4] = executor.execute(env, TRANSFER_ELF).unwrap().journal.decode().unwrap();
    let [_, _, sender_post, receiver_post] = result;

    println!("sender_before: {:?}, sender_after: {:?}", sender, sender_post);
    println!("receiver_before: {:?}, receiver_after: {:?}", receiver, receiver_post);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_private() {
        run_private_execution_of_transfer_program();
    }

    #[test]
    fn test_public() {
        run_public_execution_of_transfer_program();
    }
}
