[package]
name = "xchacha20"
version = "0.1.0"
edition = "2021"
publish = false
# Ensure staticlib for RISC-V
crate-type = ["staticlib"]

[dependencies]
# no_std stream cipher
xchacha20 = { version = "0.9", default-features = false }
cipher   = { version = "0.5", default-features = false }

risc0-zkvm-guest = "2.2"

[features]
default = ["alloc"]    # pull in alloc inside guest
alloc = []

