[package]
name    = "host"
version = "0.1.0"
edition = "2021"
build   = "build.rs"

[dependencies]
risc0-zkvm  = { version = "2.3.1", features = ["std"] }
hex         = "0.4"

[build-dependencies]
risc0-build = "2.3.1"

[package.metadata.risc0]
methods = ["/Users/mellaz/Documents/nssa-zkvms/nescience-zkvm-testing/encryption-demo/guest"]
