//use std::time::Instant;

use methods::NEBRA0_GUEST_ELF;
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification
use risc0_zkvm::{default_prover, ExecutorEnv};

use pasta_curves::group::Group;

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    //tracing_subscriber::fmt()
     //   .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
    //    .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // An default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    let g1 = pasta_curves::pallas::Point::generator();
    let g2 = g1 + g1;
    let g3 = g1 + g2;
    let g4 = g1 + g3;
    let g5 = g1 + g4;
    //should be public inputs...eventually


      //  let elapsed = now.elapsed();

    
   // let inputs: Inputs = (
     //   g1, g2, g3, g4, g5,
        //a1.to_repr(),
        //a2.to_repr(),
        //b1.to_repr(),
        //b2.to_repr(),
        //x2_minus_x1_inv.to_repr(),
   // );

    //let now = Instant::now();
    let env = ExecutorEnv::builder()
        //.write(&inputs)
        //.unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Produce a receipt by proving the specified ELF binary.
    //let now = Instant::now();
    let receipt = prover.prove(env, NEBRA0_GUEST_ELF).unwrap();
    //println!("proving time: {:?}", now.elapsed());
}
